parameters:
  - name: config_object
    type: object
    default:
      property_1: "this is a test!!!"

jobs:
  - deployment: DeployAzSQLConfiguration
    displayName: Deploy Azure SQL Configuration
    pool:
      vmImage: 'ubuntu-latest'
    environment: "env-devtest-cpy"
    strategy:
      runOnce:
        deploy:
          steps:
            - template: ./steps/configure.yml
              parameters:
                config_object: "${{ parameters.config_object }}"
            - template: ./steps/test.yml