parameters:
  - name: config_object
    type: object
      - property_1: "this is a test!!!"

jobs:
  - deployment: DeployAzSQLConfiguration
    displayName: Deploy Azure SQL Configuration
    pool:
      vmImage: 'ubuntu-latest'
    environment: "env-devtest-cpy"
    strategy:
      runOnce:
        deploy:
          steps:
            - template: ./steps/configure.yml
            - template: ./steps/test.yml