steps:
  - task: Bash@3
    displayName: "Say Hello from Configuration"
    inputs:
      env:
        PROP_1:  ${{ parameters.config_object[0] }}
      targetType: 'inline'
      script: 'echo "Hello from Configuration -> ${PROP_1}"'
      failOnStdErr: true