steps:
  - task: Bash@3
    displayName: "Say Hello from Configuration"
    inputs:
      targetType: 'inline'
      script: 'echo "Hello from Configuration -> ${PROP_1}"'
      failOnStdErr: true
    env:
        PROP_1:  "$(config_object.property_1)"