name: Configure Data Product
trigger: none
pr: none

stages:
  - stage: Retrive_Configuration
    displayName: Retrive Configuration
    jobs:
      - template: ./jobs/git_repos/job.yml

  - stage: Configure_DevTest
    variables:
      - template: /ado/vars/test-config.yml@self
    jobs:
      - template: ./jobs/azure-sql-db/job.yml

