name: Configure Data Product
trigger: none
pr: none

stages:
  - stage: Configure_DevTest
    variables:
      - template: vars/test-config.yml
    jobs:
      - template: ./jobs/azure-sql-db/job.yml


