name: Configure Data Product
trigger: none
pr: none

stages:
  - stage: Retrive_Configurations
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        clean: true

  - stage: Configure_DevTest
    variables:
      - template: vars/test-config.yml
    jobs:
      - template: ./jobs/azure-sql-db/job.yml


