name: Configure Data Product
trigger: none
pr: none

stages:
  - stage: Configure
    jobs:
      - template: ./jobs/azure-sql-db/job.yml
      - template: ./jobs/azure-key-vault/job.yml
  - stage: "Configure 2"
    jobs:
      - template: ./jobs/azure-sql-db/job.yml
      - template: ./jobs/azure-key-vault/job.yml

