name: Configure Data Product
trigger: none
pr: none

stages:
  - stage: Configure_DevTest
    jobs:
      - template: ./jobs/azure-sql-db/job.yml
        parameters: 
          conf_object:
            property_1: "This is a test!!!"

