name: Configure Data Product
trigger: none
pr: none

stages:
  - stage: Configure_DevTest
    variables:
      - name: config_object
        value:
          property_1: "HELLO from configuration.yml" 
    jobs:
      - template: ./jobs/azure-sql-db/job.yml


