name: Configure Data Product
trigger: none
pr: none

stages:
  - stage: Retrive_Configuration
    displayName: Retrive Configuration
    jobs:
      - deployment: 
        displayName: Retrive Data Product Configuration
        pool:
          vmImage: 'ubuntu-latest'
        environment: "env-devtest-cpy"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  path: current_repo
                  clean: true

  - stage: Configure_DevTest
    variables:
      - template: ../current_repo/vars/test-config.yml
    jobs:
      - template: ./jobs/azure-sql-db/job.yml


